---
version: "3.9"

services:
  tima-full:
    build: "."
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 8G
    image: adafede/tima-r
    networks:
      - service-service-frontend
    security_opt:
      - apparmor:unconfined
      - no-new-privileges:true
    volumes:
      - "./data:/data"
      - "./inst:/inst"
    command: Rscript inst/scripts/tima_full.R

  tima-gui:
    build: "."
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 8G
    ports:
      - "127.0.0.1:3838:3838"
      - "127.0.0.1:3839:3839"
    image: adafede/tima-r
    networks:
      - service-service-frontend
    security_opt:
      - apparmor:unconfined
      - no-new-privileges:true
    volumes:
      - "./data:/data"
      - "./inst:/inst"
    command: Rscript inst/scripts/run_app_docker.R

  tima-mini:
    build: "."
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 8G
    image: adafede/tima-r
    networks:
      - service-service-frontend
    security_opt:
      - apparmor:unconfined
      - no-new-privileges:true
    volumes:
      - "./data:/data"
      - "./inst:/inst"
    command: Rscript inst/scripts/tima_mini.R

networks:
  service-service-frontend:
