# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
# ADD YOUR CUSTOM ENV VARIABLES HERE OR DEFINE THEM IN A FILE .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
APPLY_FIXES: all
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - R_LINTR
  - REPOSITORY_CHECKOV
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - SPELL_CSPELL
MARKDOWN_FILTER_REGEX_EXCLUDE: '(LICENSE\.md|docs/NEWS\.md)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
PRE_COMMANDS:
  - command: R --slave -e 'install.packages(c("lintr"))'
    cwd: "root"
PRINT_ALL_FILES: false
