---
name: External Use

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"
  workflow_dispatch:

permissions: read-all

jobs:
  tima-test:
    name: tima-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          Ncpus: 2

      - name: Install package
        run: |
          Rscript inst/scripts/install.R
          
      - name: Run tests
        run: |
          Rscript inst/scripts/tima_mini.R
          # Check if targets works correctly
          Rscript inst/scripts/tima_mini.R
